# REACT
FROM node:22-alpine AS builder
WORKDIR app/
COPY package*.json .
RUN npm ci
COPY . . 
RUN npm run build

# NGINX
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY cache.conf /etc/nginx/conf.d/cache.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]